package main

import (
	"flag"
	"fmt"
	"golang-webapi/conf"
	"golang-webapi/dependency"
	"golang-webapi/middleware"
	"golang-webapi/route"
	"golang-webapi/utils"

	// swagger middleware for Iris
	// swagger embed files
	"github.com/kataras/iris/v12"
	//_ "golang-webapi/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:9000
// @BasePath /
func main() {
	t := flag.CommandLine.String("conf", "json", "conf type: json yaml toml")
	flag.Parse()

	cfg := conf.ReadConf(conf.ParseConfType(*t))

	app := iris.New()
	app.Logger().SetLevel(cfg.Level)
	app.Configure(iris.WithConfiguration(cfg.Configuration))

	app.UseGlobal(middleware.Debug)
	app.OnAnyErrorCode(func(ctx iris.Context) {
		if ctx.GetStatusCode() == iris.StatusNotFound {
			ctx.JSON(utils.NotFoundErr.WithMessage(fmt.Sprintf("route[%v] not found", ctx.Path())))
		} else {
			ctx.JSON(utils.ServeErr.WithMessage(fmt.Sprintf("invoke route[%v] err", ctx.Path())))
		}
	})
	middleware.RecoverHandler = func(ctx iris.Context, err interface{}) {
		ctx.Application().Logger().Warn(fmt.Sprintf("Recovered from a route's Handler('%s'), Exception: %v", ctx.RouteName(), err))

		if ex, ok := err.(*utils.BusinessException); !ok {
			ctx.JSON(utils.ServeErr.WithMessage(fmt.Sprintf("%s: %v", utils.ServeErr.Message, err)))
		} else {
			ctx.JSON(ex)
		}
	}

	// use swagger middleware to
	//app.Get("/swagger/{any:path}", swagger.WrapHandler(swaggerFiles.Handler))

	route.Handle(app, dependency.GetDependencies(cfg)...)
	app.Listen(
		":"+fmt.Sprintf("%v", cfg.Port),
		iris.WithOptimizations,
		iris.WithoutBodyConsumptionOnUnmarshal,
		iris.WithoutServerError(iris.ErrServerClosed),
	)
	//app.NewHost(&http.Server{Addr: ":8080"}).ListenAndServe()
}
